version: "3.7"

services:
  apache:
    hostname: apache
    build: apache
    volumes:
      - ./app:/var/www/html
    ports:
      - 880:80
      - 8443:443
    depends_on:
      - wordpress
  wordpress:
    hostname: wordpress
    build: wordpress
    volumes:
      - ./app:/var/www/html
    ports:
      - 9000:9000
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WP_DEBUG: 1
      LIVE_URL: https://live.bloemendaal.dev
      DEV_URL: http://dev.bloemendaal.dev
  mysql:
    hostname: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    command: [
      '--default_authentication_plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

volumes:
  db_data: {}

